# Generated by Django 4.2.7 on 2025-11-05 03:10

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('perfil', models.CharField(choices=[('VENDEDOR', 'Vendedor'), ('RESPONSAVEL', 'Responsável de Canal'), ('ADMIN', 'Administrador')], default='VENDEDOR', max_length=20)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
                'ordering': ['first_name', 'last_name'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Conta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_empresa', models.CharField(max_length=255)),
                ('cnpj', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('telefone_principal', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('setor', models.CharField(blank=True, max_length=100, null=True)),
                ('endereco', models.CharField(blank=True, max_length=255, null=True)),
                ('cidade', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(blank=True, max_length=2, null=True)),
                ('cep', models.CharField(blank=True, max_length=10, null=True)),
                ('notas', models.TextField(blank=True, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('proprietario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conta',
                'verbose_name_plural': 'Contas',
                'ordering': ['nome_empresa'],
            },
        ),
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, validators=[django.core.validators.EmailValidator()])),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('celular', models.CharField(blank=True, max_length=20, null=True)),
                ('cargo', models.CharField(blank=True, max_length=100, null=True)),
                ('departamento', models.CharField(blank=True, max_length=100, null=True)),
                ('notas', models.TextField(blank=True, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contatos', to='crm.conta')),
                ('proprietario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contatos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contato',
                'verbose_name_plural': 'Contatos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='EstagioFunil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('tipo', models.CharField(choices=[('ABERTO', 'Aberto'), ('GANHO', 'Fechado - Ganho'), ('PERDIDO', 'Fechado - Perdido')], default='ABERTO', max_length=20)),
                ('cor', models.CharField(default='#3B82F6', help_text='Cor em hexadecimal', max_length=7)),
            ],
            options={
                'verbose_name': 'Estágio do Funil',
                'verbose_name_plural': 'Estágios do Funil',
                'ordering': ['ordem'],
                'unique_together': {('nome',)},
            },
        ),
        migrations.CreateModel(
            name='Canal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('responsavel', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='canal_responsavel', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Canal',
                'verbose_name_plural': 'Canais',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('TAREFA', 'Tarefa'), ('LIGACAO', 'Ligação'), ('REUNIAO', 'Reunião'), ('EMAIL', 'E-mail'), ('NOTA', 'Nota')], max_length=20)),
                ('titulo', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('data_vencimento', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Pendente', 'Pendente'), ('Concluída', 'Concluída'), ('Cancelada', 'Cancelada')], default='Pendente', max_length=20)),
                ('object_id', models.PositiveIntegerField()),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('data_conclusao', models.DateTimeField(blank=True, null=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('proprietario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='atividades', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Atividade',
                'verbose_name_plural': 'Atividades',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='canal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendedores', to='crm.canal'),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.CreateModel(
            name='Oportunidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('valor_estimado', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('data_fechamento_esperada', models.DateField(blank=True, null=True)),
                ('probabilidade', models.PositiveIntegerField(default=0, help_text='Probabilidade de fechamento (0-100%)')),
                ('descricao', models.TextField(blank=True, null=True)),
                ('motivo_perda', models.TextField(blank=True, null=True)),
                ('data_fechamento_real', models.DateField(blank=True, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oportunidades', to='crm.conta')),
                ('contato_principal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oportunidades', to='crm.contato')),
                ('estagio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='oportunidades', to='crm.estagiofunil')),
                ('proprietario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='oportunidades', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Oportunidade',
                'verbose_name_plural': 'Oportunidades',
                'ordering': ['-data_criacao'],
                'indexes': [models.Index(fields=['proprietario', 'estagio'], name='crm_oportun_proprie_61651e_idx'), models.Index(fields=['conta'], name='crm_oportun_conta_i_77334b_idx')],
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, validators=[django.core.validators.EmailValidator()])),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('empresa', models.CharField(blank=True, max_length=255, null=True)),
                ('cargo', models.CharField(blank=True, max_length=100, null=True)),
                ('fonte', models.CharField(blank=True, help_text='Ex: Site, Evento, Indicação', max_length=100, null=True)),
                ('status', models.CharField(choices=[('Novo', 'Novo'), ('Contatado', 'Contatado'), ('Qualificado', 'Qualificado'), ('Convertido', 'Convertido'), ('Descartado', 'Descartado')], default='Novo', max_length=20)),
                ('notas', models.TextField(blank=True, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('proprietario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lead',
                'verbose_name_plural': 'Leads',
                'ordering': ['-data_criacao'],
                'indexes': [models.Index(fields=['proprietario', 'status'], name='crm_lead_proprie_ae1f0d_idx'), models.Index(fields=['email'], name='crm_lead_email_57c21b_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='contato',
            index=models.Index(fields=['proprietario', 'conta'], name='crm_contato_proprie_ed3dc5_idx'),
        ),
        migrations.AddIndex(
            model_name='contato',
            index=models.Index(fields=['email'], name='crm_contato_email_d5f260_idx'),
        ),
        migrations.AddIndex(
            model_name='conta',
            index=models.Index(fields=['proprietario'], name='crm_conta_proprie_f1f3b4_idx'),
        ),
        migrations.AddIndex(
            model_name='conta',
            index=models.Index(fields=['cnpj'], name='crm_conta_cnpj_97cb4e_idx'),
        ),
        migrations.AddIndex(
            model_name='atividade',
            index=models.Index(fields=['proprietario', 'status'], name='crm_ativida_proprie_e82930_idx'),
        ),
        migrations.AddIndex(
            model_name='atividade',
            index=models.Index(fields=['content_type', 'object_id'], name='crm_ativida_content_48da7d_idx'),
        ),
    ]
