# Generated by Django 4.2.7 on 2025-12-24 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosticoPergunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('ajuda', models.TextField(blank=True, help_text='Texto de ajuda ou explicação da pergunta', null=True)),
            ],
            options={
                'verbose_name': 'Pergunta do Diagnóstico',
                'verbose_name_plural': 'Perguntas do Diagnóstico',
                'ordering': ['pilar__ordem', 'ordem'],
            },
        ),
        migrations.CreateModel(
            name='DiagnosticoPilar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('cor', models.CharField(default='#3B82F6', help_text='Cor em hexadecimal para o gráfico', max_length=7)),
            ],
            options={
                'verbose_name': 'Pilar do Diagnóstico',
                'verbose_name_plural': 'Pilares do Diagnóstico',
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='DiagnosticoResultado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_conclusao', models.DateTimeField(auto_now_add=True)),
                ('respostas_detalhadas', models.JSONField(help_text='JSON com as perguntas e respostas escolhidas')),
                ('pontuacao_por_pilar', models.JSONField(help_text='JSON com {pilar_nome: score}')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnosticos', to='crm.lead')),
            ],
            options={
                'verbose_name': 'Resultado do Diagnóstico',
                'verbose_name_plural': 'Resultados do Diagnóstico',
                'ordering': ['-data_conclusao'],
            },
        ),
        migrations.CreateModel(
            name='DiagnosticoResposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('pontuacao', models.IntegerField(default=0, help_text='Pontuação de 0 a 10')),
                ('feedback', models.TextField(blank=True, help_text='Feedback específico para esta resposta', null=True)),
                ('pergunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='crm.diagnosticopergunta')),
            ],
            options={
                'verbose_name': 'Resposta do Diagnóstico',
                'verbose_name_plural': 'Respostas do Diagnóstico',
                'ordering': ['pergunta', 'pontuacao'],
            },
        ),
        migrations.AddField(
            model_name='diagnosticopergunta',
            name='pilar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perguntas', to='crm.diagnosticopilar'),
        ),
    ]
