# Generated by Django 4.2.7 on 2025-12-26 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_diagnosticopergunta_diagnosticopilar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosticoresultado',
            name='conta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diagnosticos', to='crm.conta'),
        ),
        migrations.AlterField(
            model_name='diagnosticoresultado',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diagnosticos', to='crm.lead'),
        ),
    ]
